# Kubernetes Service for simple-server
apiVersion: v1
kind: Service
metadata:
  namespace: simple-server
  name: simple-server
  labels:
    app: simple-server
spec:
  type: ClusterIP
  selector:
    app: simple-server
  ports:
    - port: 80          # <- clients (Ingress) connect here
      targetPort: 8080  # <- forwards to pod's containerPort
      protocol: TCP
